name: CI
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main

jobs:
  project:
    name: Project Tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Install QEMU
        uses: docker/setup-qemu-action@v2
        id: qemu

      - name: Install BUILDX
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run demo test
        id: test
        run: ai-model-registry/hack/run